### ISSUE TITLE
Publish on ansible galaxy

### ISSUE THREAD

**Issue by dylancwood** [cw-ansible/cw.mmonit#1]
Thanks for publishing this repo on github. In order to make it more accessible to Ansible users, would you be willing to publish it on ansiblegalaxy? If you're not interested, would you be alright with me putting it up there?

**Comment by renard** [comment]
I haven't yet read about ansible galaxy usage. If you provide the correct yaml file it would be easy to publish it on AG.
If you don't I'll do it in a few days. Just back from vacations.

**Comment by kh0r** [comment]
More info can be found here: https://galaxy.ansible.com/intro#share
